### ISSUE TITLE
code no longer works

### ISSUE THREAD

**Issue by funkytaco** [Kanasansoft/Pick-Photo-from-Web-Camera#1]
This doesn't seem to work now. RTC specs may have changed.

**Comment by Kanasansoft** [comment]
Thanks for your issue report.

getUserMedia(one of WebRTC API) is a usable.
But, Web Intents was removed from Google Chrome.
(Web Intents is experimental API in Google Chrome).
Because, This API has UI/UX issue.
(I think this api will be Implemented again.)

**Comment by funkytaco** [comment]
Deprecated, I guess. Closing.
